# Generated by Django 3.1.7 on 2021-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentController', '0002_documentedits_editisvalid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentedits',
            constraint=models.UniqueConstraint(fields=('userId', 'documentId'), name='unique edits'),
        ),
    ]
